export * from './mutations/events.mutations'
export * from './mutations/registrations.mutations'
export * from './mutations/interests.mutations'
export * from './mutations/feedback.mutations'
export * from './mutations/users.mutations'
export * from './mutations/auth.mutations'
